### ISSUE TITLE
Add https support

### ISSUE THREAD

**Issue by linux-china** [rsocket/rsocket-website#16]
RSocket is a safe protocol and site should be safe first  :)  Please consider to use https://letsencrypt.org/

**Comment by kedar-joshi** [comment]
HTTPS is by default supported with Github pages -

https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

**Comment by flyinprogrammer** [comment]
We're so close to getting this fixed.

Someone needs to go into this repo and check the "Enforce HTTPS" checkbox so that HTTP requests get [redirected to HTTPS](https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site).

Similarly the A record for rsocket.io has some potential poison in it:

```
dig @8.8.8.8 rsocket.io +short
185.199.108.153
192.30.252.153
```

we should make sure the A record has [these addresses](https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain) in it:

```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

**Comment by kedar-joshi** [comment]
@linux-china I think the A records were not added as suggested by @flyinprogrammer -

> we should make sure the A record has [these addresses](https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain) in it:
> 
> ```
> 185.199.108.153
> 185.199.109.153
> 185.199.110.153
> 185.199.111.153
> ```

**Comment by flyinprogrammer** [comment]
@rdegnan this is still broken

**Comment by haal** [comment]
It seems HTTPS is working on rocket.io

**Comment by OlegDokuka** [comment]
It is fixed now
